#!/usr/bin/env bash
set -e
set -u
set -o pipefail

# Check if no arguments were provided ($# is 0)
if [ $# -eq 0 ]; then
  echo "Available choices:"
  echo "* lofi"
  echo "* trance"
  echo "* salsa"
  echo "* kfai"
  exit 0 # Exit successfully after showing choices
fi

# Use a case statement for cleaner argument parsing
case "$1" in
  lofi)
    url='https://live.hunter.fm/lofi_low'
    ;;
  trance)
    url='http://ubuntu.hbr1.com:19800/trance.ogg'
    ;;
  salsa)
    url='https://latinasalsa.ice.infomaniak.ch/latinasalsa.mp3'
    ;;
  kfai)
    url='https://kfai.broadcasttool.stream/kfai-1'
    ;;
  *) # Default case if argument is not recognized
    echo "Error: don't know $1" 1>&2
    exit 1
    ;;
esac

echo "Playing $1 from ${url}..."
exec mpv --really-quiet "$url"
MPV_EXIT_CODE=$?

# If mpv's exit code is 4 (the value you observe on Ctrl+C)
if [ "$MPV_EXIT_CODE" -eq 4 ]; then
    exit 0
else
    exit "$MPV_EXIT_CODE"
fi
